/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import static bank.TransferGUI.transferGUI;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author adamstreich
 */
public class CustomerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CustomerGUI
     */
    public CustomerGUI(Customer cs, Bank bnk) {
        initComponents();
        initCustom(cs);
        initActionListensers(cs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jFrame5 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        chekAccList1 = new javax.swing.JComboBox<>();
        chekAccListLabel1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        chekAccBalanceDisplay1 = new javax.swing.JTextField();
        chekAccBalanceLabel1 = new javax.swing.JLabel();
        updateCurrentChekAccButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        withdrawChekAccButton1 = new javax.swing.JButton();
        depositChekAccButton1 = new javax.swing.JButton();
        interactionFieldChekAcc1 = new javax.swing.JTextField();
        InteractChekAccLabel1 = new javax.swing.JLabel();
        chekAccTransferButton = new javax.swing.JButton();
        tHistoryCheAccPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        cheAccTextBox1 = new javax.swing.JTextArea();
        cheAccTranHistLabel1 = new javax.swing.JLabel();
        cheAccTHShowAllButton1 = new javax.swing.JButton();
        cheAccTHInRangeButton1 = new javax.swing.JButton();
        cheAccTHDate0Field1 = new javax.swing.JTextField();
        cheAccTHDate1Field1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        sAccList = new javax.swing.JComboBox<>();
        savAccListLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        savAccBalanceDisplay = new javax.swing.JTextField();
        savAccBalanceLabel = new javax.swing.JLabel();
        updateCurrentSavAccButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        withdrawSaAccButton = new javax.swing.JButton();
        depositSaAccButton = new javax.swing.JButton();
        interactionFieldSaAcc = new javax.swing.JTextField();
        InteractSaAccLabel = new javax.swing.JLabel();
        savAccTHistPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        savAccTextBox = new javax.swing.JTextArea();
        savAccTranHistLabel = new javax.swing.JLabel();
        savAccTHShowAllButton = new javax.swing.JButton();
        savAccTHInRangeButton = new javax.swing.JButton();
        savAccTHDate0Field = new javax.swing.JTextField();
        savAccTHDate1Field = new javax.swing.JTextField();
        savAccTransferButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        openNewAccButton = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame5Layout = new javax.swing.GroupLayout(jFrame5.getContentPane());
        jFrame5.getContentPane().setLayout(jFrame5Layout);
        jFrame5Layout.setHorizontalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame5Layout.setVerticalGroup(
            jFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chekAccListLabel1.setText("Select an account to work with, then hit Bank:");

        chekAccBalanceDisplay1.setEditable(false);

        chekAccBalanceLabel1.setText("Account Balance");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chekAccBalanceLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chekAccBalanceDisplay1))
                .addGap(22, 22, 22))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(chekAccBalanceLabel1)
                .addGap(18, 18, 18)
                .addComponent(chekAccBalanceDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        updateCurrentChekAccButton1.setText("Bank");

        withdrawChekAccButton1.setText("Withdraw");

        depositChekAccButton1.setText("Deposit");

        interactionFieldChekAcc1.setFont(new java.awt.Font("Apple Color Emoji", 0, 13)); // NOI18N
        interactionFieldChekAcc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interactionFieldChekAcc1ActionPerformed(evt);
            }
        });

        InteractChekAccLabel1.setText("Interact Below:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawChekAccButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositChekAccButton1)
                .addGap(12, 12, 12))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(interactionFieldChekAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(InteractChekAccLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(InteractChekAccLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interactionFieldChekAcc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawChekAccButton1)
                    .addComponent(depositChekAccButton1))
                .addContainerGap())
        );

        chekAccTransferButton.setText("Transfer");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chekAccListLabel1)
                            .addComponent(chekAccList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(updateCurrentChekAccButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(chekAccTransferButton)
                        .addGap(104, 104, 104)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(484, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(chekAccListLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chekAccList1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateCurrentChekAccButton1))
                .addGap(48, 48, 48)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chekAccTransferButton)
                        .addGap(33, 33, 33))))
        );

        cheAccTextBox1.setEditable(false);
        cheAccTextBox1.setColumns(20);
        cheAccTextBox1.setRows(5);
        jScrollPane2.setViewportView(cheAccTextBox1);

        cheAccTranHistLabel1.setText("Transaction History");

        cheAccTHShowAllButton1.setText("Show All");

        cheAccTHInRangeButton1.setText("In Range");

        cheAccTHDate0Field1.setText("yyyy-mm-dd");

        cheAccTHDate1Field1.setText("yyyy-mm-dd");

        javax.swing.GroupLayout tHistoryCheAccPanelLayout = new javax.swing.GroupLayout(tHistoryCheAccPanel);
        tHistoryCheAccPanel.setLayout(tHistoryCheAccPanelLayout);
        tHistoryCheAccPanelLayout.setHorizontalGroup(
            tHistoryCheAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tHistoryCheAccPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cheAccTranHistLabel1)
                .addGap(86, 86, 86))
            .addGroup(tHistoryCheAccPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tHistoryCheAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tHistoryCheAccPanelLayout.createSequentialGroup()
                        .addComponent(cheAccTHDate0Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(tHistoryCheAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cheAccTHInRangeButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cheAccTHShowAllButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cheAccTHDate1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tHistoryCheAccPanelLayout.setVerticalGroup(
            tHistoryCheAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tHistoryCheAccPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(cheAccTranHistLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheAccTHShowAllButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tHistoryCheAccPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheAccTHDate0Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheAccTHDate1Field1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheAccTHInRangeButton1))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(568, Short.MAX_VALUE)
                .addComponent(tHistoryCheAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(tHistoryCheAccPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 18, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 19, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Checking Accounts", jPanel2);

        savAccListLabel.setText("Select an account to work with, then hit Bank:");

        savAccBalanceDisplay.setEditable(false);

        savAccBalanceLabel.setText("Account Balance");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(savAccBalanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(savAccBalanceDisplay))
                .addGap(22, 22, 22))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(savAccBalanceLabel)
                .addGap(18, 18, 18)
                .addComponent(savAccBalanceDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        updateCurrentSavAccButton.setText("Bank");

        withdrawSaAccButton.setText("Withdraw");

        depositSaAccButton.setText("Deposit");

        interactionFieldSaAcc.setFont(new java.awt.Font("Apple Color Emoji", 0, 13)); // NOI18N
        interactionFieldSaAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interactionFieldSaAccActionPerformed(evt);
            }
        });

        InteractSaAccLabel.setText("Interact Below:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(withdrawSaAccButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositSaAccButton)
                .addGap(12, 12, 12))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(interactionFieldSaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(InteractSaAccLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(InteractSaAccLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(interactionFieldSaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawSaAccButton)
                    .addComponent(depositSaAccButton))
                .addContainerGap())
        );

        savAccTextBox.setEditable(false);
        savAccTextBox.setColumns(20);
        savAccTextBox.setRows(5);
        jScrollPane1.setViewportView(savAccTextBox);

        savAccTranHistLabel.setText("Transaction History");

        savAccTHShowAllButton.setText("Show All");

        savAccTHInRangeButton.setText("In Range");

        savAccTHDate0Field.setText("mm/dd/yyyy");

        savAccTHDate1Field.setText("mm/dd/yyyy");

        javax.swing.GroupLayout savAccTHistPanelLayout = new javax.swing.GroupLayout(savAccTHistPanel);
        savAccTHistPanel.setLayout(savAccTHistPanelLayout);
        savAccTHistPanelLayout.setHorizontalGroup(
            savAccTHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savAccTHistPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(savAccTranHistLabel)
                .addGap(86, 86, 86))
            .addGroup(savAccTHistPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(savAccTHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(savAccTHistPanelLayout.createSequentialGroup()
                        .addComponent(savAccTHDate0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(savAccTHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(savAccTHInRangeButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(savAccTHShowAllButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(savAccTHDate1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        savAccTHistPanelLayout.setVerticalGroup(
            savAccTHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savAccTHistPanelLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(savAccTranHistLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savAccTHShowAllButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savAccTHistPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savAccTHDate0Field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savAccTHDate1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savAccTHInRangeButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        savAccTHDate1Field.getAccessibleContext().setAccessibleName("");

        savAccTransferButton1.setText("Transfer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(savAccListLabel)
                                    .addComponent(sAccList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(updateCurrentSavAccButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(savAccTransferButton1)
                                .addGap(108, 108, 108)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)))
                .addComponent(savAccTHistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(savAccListLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sAccList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(updateCurrentSavAccButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(savAccTransferButton1)
                                .addGap(14, 14, 14))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(savAccTHistPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Savings Accounts", jPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Securities Accounts", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 936, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 371, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Loans", jPanel4);

        openNewAccButton.setText("Open New Account");
        openNewAccButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNewAccButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(openNewAccButton)
                .addContainerGap(756, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(openNewAccButton)
                .addContainerGap(325, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Options", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void interactionFieldSaAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interactionFieldSaAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interactionFieldSaAccActionPerformed

    private void interactionFieldChekAcc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interactionFieldChekAcc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interactionFieldChekAcc1ActionPerformed

    private void openNewAccButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNewAccButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openNewAccButtonActionPerformed
    
    //builds the gui for the user in the begining
    public void initCustom(Customer user){
        this.updateSavingsAccList(user);
        this.updateSavingsAccBalanceDisp(user);
        this.updateCheckingAccList(user);
        this.updateCheckingAccBalanceDisp(user);
        
        
    }
    
    //builds the action listeners
    private void initActionListensers(Customer user){
        //savings account action listeners
        //
        //update what savings account is being banked in 
        updateCurrentSavAccButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateWorkingSavingsAcc(user);
            }
                
        });
        
        //deposit to the savings account
        depositSaAccButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                depositSaAcc(user);
            }
                
        });
        
        //withdraw from the savings account
        withdrawSaAccButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawSaAcc(user);
            }
                
        });
        
        //Checking Account action listeners
        //
        
        //update what checking account is being banked in 
        updateCurrentChekAccButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                updateworkingCheckingAcc(user);
            }
                
        });
        
        //deposit to the Checking account
        depositChekAccButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                depositChekAcc(user);
            }
                
        });
        
        //withdraw from the Check account
        withdrawChekAccButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                withdrawChekAcc(user);
            }
                
        });
        
        chekAccTransferButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                transferChekAcc(user);
            }
                
        });
        
        savAccTransferButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                transferSavAcc(user);
            }
                
        });
        
    }
    
    
    
    //Savings account methods
    //
    
    
    
    //updates the savings accounts in the list
    public void updateSavingsAccList(Customer user){
        Iterator SAiter = user.getSASIter();
        while(SAiter.hasNext()){
            SavingsAccount sa = (SavingsAccount) SAiter.next();
            sAccList.addItem(sa.getName());
            sAccList.getSelectedIndex();
        }
    }
    
    //updates the balance that is diplayed, but needs a action listener to call it
    public void updateSavingsAccBalanceDisp(Customer user){
        int indexOfAcc = sAccList.getSelectedIndex();
        SavingsAccount acc = user.getSavingsAccounts().get(indexOfAcc);
        String disp = acc.currency.getSymbol() + " " + acc.getBalance();
        savAccBalanceDisplay.setText(disp);
        
    }
    
    //the method called in the action listener
    public void updateWorkingSavingsAcc(Customer user){
        this.updateSavingsAccBalanceDisp(user);
        this.updateTHSavAcc(user);
    }
    
    public void depositSaAcc(Customer user){
        int indexOfAcc = sAccList.getSelectedIndex();
        SavingsAccount acc = user.getSavingsAccounts().get(indexOfAcc);
        try{
            double inp = Double.parseDouble(interactionFieldSaAcc.getText());
            System.out.println(inp + " will be taken from the current account.");
            acc.deposit(inp);
        }catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            System.out.println("User tried to enter not a double");
        }
        updateWorkingSavingsAcc(user);
        interactionFieldSaAcc.setText(" ");
    }
    
    public void withdrawSaAcc(Customer user){
       int indexOfAcc = sAccList.getSelectedIndex();
        SavingsAccount acc = user.getSavingsAccounts().get(indexOfAcc);
        try{
            double inp = Double.parseDouble(interactionFieldSaAcc.getText());
            System.out.println(inp + " will be added to the current account.");
            acc.withdraw(inp);
            
        }catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            System.out.println("User tried to enter not a double");
        }
        updateWorkingSavingsAcc(user);
        interactionFieldSaAcc.setText(" ");
        
    }
    
    public void updateTHSavAcc(Customer user){
        savAccTextBox.setText(" ");
        String th = "";
        int indexOfAcc = sAccList.getSelectedIndex();
        SavingsAccount acc = user.getSavingsAccounts().get(indexOfAcc);
        
        Iterator iter = acc.transactions.iterator();
        while(iter.hasNext()){
            Transaction t = (Transaction) iter.next();
            th+= t.toString() + " \n";
        }
        savAccTextBox.setText(th);
    }
    
    public void transferSavAcc(Customer user){
        int indexOfAcc = chekAccList1.getSelectedIndex();
        SavingsAccount acc = user.getSavingsAccounts().get(indexOfAcc);
        transferGUI(acc,user,this);
        
        interactionFieldChekAcc1.setText(" ");
        
    }
    
  
    
    
    
    
    
    //Checking account methods
    //
    
    //updates the Checking accounts in the list
    public void updateCheckingAccList(Customer user){
        Iterator CAiter = user.getCEKAIter();
        while(CAiter.hasNext()){
            CheckingAccount sa = (CheckingAccount) CAiter.next();
            chekAccList1.addItem(sa.getName());
        }
    }
    
    //updates the balance that is diplayed, but needs a action listener to call it
    public void updateCheckingAccBalanceDisp(Customer user){
        int indexOfAcc = chekAccList1.getSelectedIndex();
        CheckingAccount acc = user.getCheckingAccounts().get(indexOfAcc);
        String disp = acc.currency.getSymbol() + " " + acc.getBalance();
        chekAccBalanceDisplay1.setText(disp);
        
    }
    
    //the method called in the action listener
    public void updateworkingCheckingAcc(Customer user){
        this.updateCheckingAccBalanceDisp(user);
        this.updateTHChekAcc(user);
    }
    
    public void depositChekAcc(Customer user){
        int indexOfAcc = chekAccList1.getSelectedIndex();
        System.out.println(indexOfAcc);
        CheckingAccount acc = user.getCheckingAccounts().get(indexOfAcc);
        System.out.println(acc.toString());
        try{
            double inp = Double.parseDouble(interactionFieldChekAcc1.getText());
            System.out.println(inp + " will be taken from the current account.");
            acc.deposit(inp);
        }catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            System.out.println("User tried to enter not a double");
        }
        updateworkingCheckingAcc(user);
        interactionFieldChekAcc1.setText(" ");
    }
    
    public void withdrawChekAcc(Customer user){
        int indexOfAcc = chekAccList1.getSelectedIndex();
        CheckingAccount acc = user.getCheckingAccounts().get(indexOfAcc);
        try{
            double inp = Double.parseDouble(interactionFieldChekAcc1.getText());
            System.out.println(inp + " will be added to the current account.");
            acc.withdraw(inp);
            
        }catch(NumberFormatException ex){
            System.out.println(ex.getMessage());
            System.out.println("User tried to enter not a double");
        }
        updateworkingCheckingAcc(user);
        interactionFieldChekAcc1.setText(" ");
        
    }
    
    public void transferChekAcc(Customer user){
        int indexOfAcc = chekAccList1.getSelectedIndex();
        CheckingAccount acc = user.getCheckingAccounts().get(indexOfAcc);
        transferGUI(acc,user,this);
        
        interactionFieldChekAcc1.setText(" ");
        
    }
    
    public void updateTHChekAcc(Customer user){
        cheAccTextBox1.setText(" ");
        String th = "";
        int indexOfAcc = chekAccList1.getSelectedIndex();
        CheckingAccount acc = user.getCheckingAccounts().get(indexOfAcc);
        Iterator iter = acc.transactions.iterator();
        while(iter.hasNext()){
            Transaction t = (Transaction) iter.next();
            th+= t.toString() + " \n";
        }
        cheAccTextBox1.setText(th);
    }
    
    //general display and transaction history update method
    public void updateAllDsipAndTH(Customer user){
        this.updateworkingCheckingAcc(user);
        this.updateWorkingSavingsAcc(user);
    }
    
    //just for testing
    public static Bank getTestB(){
        
        Customer tester = bank.Customer.createCustomer("Adam","Streich","astreich","12345");
        tester.createSavingsAccount("Acc1S", "USD");
        tester.createSavingsAccount("Acc2S", "USD");
        tester.createCheckingAccount("Acc1C", "USD");
        tester.createCheckingAccount("Acc2C", "USD");
        
        Manager temp = bank.Manager.createManager("Mr.", "Monopoly", "mrMono", "12345");
        ArrayList cs = new ArrayList();
        cs.add(tester);
        Customers testers = new Customers(cs);
        
        Bank test = new Bank(testers, temp);
        Bank.setCurrentDate(LocalDate.of(2020, 04, 28));
        
        return test;
    }
    public static Customer getTestC(){
        
        Customer tester = bank.Customer.createCustomer("Adam","Streich","astreich","12345");
        tester.createSavingsAccount("Acc1S", "USD");
        tester.createSavingsAccount("Acc2S", "USD");
        tester.createCheckingAccount("Acc1C", "USD");
        tester.createCheckingAccount("Acc2C", "USD");
        
        
        return tester;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            //pull the customer from the data set
            Bank tester = getTestB();
            Customer test = getTestC();
            
            
            public void run() {
                new CustomerGUI(test,tester).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel InteractChekAccLabel1;
    private javax.swing.JLabel InteractSaAccLabel;
    private javax.swing.JTextField cheAccTHDate0Field1;
    private javax.swing.JTextField cheAccTHDate1Field1;
    private javax.swing.JButton cheAccTHInRangeButton1;
    private javax.swing.JButton cheAccTHShowAllButton1;
    private javax.swing.JTextArea cheAccTextBox1;
    private javax.swing.JLabel cheAccTranHistLabel1;
    private javax.swing.JTextField chekAccBalanceDisplay1;
    private javax.swing.JLabel chekAccBalanceLabel1;
    private javax.swing.JComboBox<String> chekAccList1;
    private javax.swing.JLabel chekAccListLabel1;
    private javax.swing.JButton chekAccTransferButton;
    private javax.swing.JButton depositChekAccButton1;
    private javax.swing.JButton depositSaAccButton;
    private javax.swing.JTextField interactionFieldChekAcc1;
    private javax.swing.JTextField interactionFieldSaAcc;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JFrame jFrame5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton openNewAccButton;
    private javax.swing.JComboBox<String> sAccList;
    private javax.swing.JTextField savAccBalanceDisplay;
    private javax.swing.JLabel savAccBalanceLabel;
    private javax.swing.JLabel savAccListLabel;
    private javax.swing.JTextField savAccTHDate0Field;
    private javax.swing.JTextField savAccTHDate1Field;
    private javax.swing.JButton savAccTHInRangeButton;
    private javax.swing.JButton savAccTHShowAllButton;
    private javax.swing.JPanel savAccTHistPanel;
    private javax.swing.JTextArea savAccTextBox;
    private javax.swing.JLabel savAccTranHistLabel;
    private javax.swing.JButton savAccTransferButton1;
    private javax.swing.JPanel tHistoryCheAccPanel;
    private javax.swing.JButton updateCurrentChekAccButton1;
    private javax.swing.JButton updateCurrentSavAccButton;
    private javax.swing.JButton withdrawChekAccButton1;
    private javax.swing.JButton withdrawSaAccButton;
    // End of variables declaration//GEN-END:variables
}
