/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank;

import static bank.Constants.curencies;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author adamstreich
 */
public class NewAccountFormGUI extends javax.swing.JPanel {

    /**
     * Creates new form NewAccountFormGUI
     */
    public NewAccountFormGUI(Customer user, CustomerGUI maingui, NewAccountGUI newaccgui, int type ) {
        initComponents();
        initCustom(user);
        initActionListeners(user,maingui,newaccgui,type);
    }

   

    public void initCustom(Customer user){
        fillCurrency();
    }
    
    private void initActionListeners( Customer user, CustomerGUI maingui, NewAccountGUI newaccgui, int type){
        
        createAccjButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                createAcc(user, maingui, newaccgui, type);
            }
                
        });
        
        
    }
    
    public void fillCurrency(){
        for(int c = 0; c < curencies.size(); c++){
            currencyjComboBox1.addItem(curencies.get(c));
        }
    }
    
    public void createAcc( Customer user, CustomerGUI maingui, NewAccountGUI newaccgui, int type){
        try{
            if (type == 0){
                System.out.println(currencyjComboBox1.getSelectedItem().toString());
                user.createCheckingAccount(accountNamejTextField.getText(), currencyjComboBox1.getSelectedItem().toString());
            }else if( type == 1){
                user.createSavingsAccount(accountNamejTextField.getText(), currencyjComboBox1.getSelectedItem().toString());
            }
            
        }catch(Exception ex){
            System.out.println(ex.getMessage());
            System.out.println("Wrong inputs");
        }
        
        newaccgui.dispose();
        maingui.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appjLabel = new javax.swing.JLabel();
        accNamejLabel = new javax.swing.JLabel();
        currencyjLabel = new javax.swing.JLabel();
        createAccjButton = new javax.swing.JButton();
        accountNamejTextField = new javax.swing.JTextField();
        currencyjComboBox1 = new javax.swing.JComboBox<>();

        appjLabel.setText("Application");

        accNamejLabel.setText("Account Name:");

        currencyjLabel.setText("Currency:");

        createAccjButton.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createAccjButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(170, 170, 170)
                            .addComponent(appjLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(currencyjLabel)
                                .addComponent(accNamejLabel)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountNamejTextField)
                    .addComponent(currencyjComboBox1, 0, 92, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appjLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accNamejLabel)
                    .addComponent(accountNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currencyjLabel)
                    .addComponent(currencyjComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(createAccjButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accNamejLabel;
    private javax.swing.JTextField accountNamejTextField;
    private javax.swing.JLabel appjLabel;
    private javax.swing.JButton createAccjButton;
    private javax.swing.JComboBox<String> currencyjComboBox1;
    private javax.swing.JLabel currencyjLabel;
    // End of variables declaration//GEN-END:variables
}
